/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample;

import com.queue.Queue;
import com.queue.ImmutableQueue;
import com.stack.Stack;
import com.stack.ImmutableStack;

public class App {

    public App() {
        try {
        } catch(Exception e) {
            System.out.println(e);
        }
    }

    public static void main(String[] args) {
        new App();
    }
}
